# Site settings
title: Bhavesh Prajapati 
description: Bhavesh Prajapati
avtar: /assets/img/avatar.jpg
favicon: /assets/img/favicon.ico
baseurl: https://bhaveshpp.github.io
url: https://bhaveshpp.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Bhavesh Prajapati
  title: Professional Magento Developer
  address: Surat, Gujarat, India
  email: bhaveshp.magento@gmail.com
  link: https://bhaveshpp.github.io
  skype: live:bhaveshpp11
  skypeurl: https://join.skype.com/invite/wBzrwCc2PXcJ
  github: bhaveshpp
  linkedin: bhavesh-prajapati-576a97171
  twitter: bhaveshpp111
  gavatar: /assets/img/avatar.JPG
  magento.stackexchange: 70292
#  stackoverflow: 70292
  workHistory:
    - work4:
      company: Individual 
      location: Remote / Worldwide
      title: Magento Developer
      started: Dec 2020
      duration: (2020 - present)
      description: Professional Fullstack Developer (Ecommerce web developer)
    - work3:
      company: Tecksky
      location: Surat, Gujarat
      title: Magento Developer
      started: Sep 2020
      duration: (2020 - 2021)
      description: Adobe Ecommerce Developer (Magento)
    - work2:
      company: Aureate Labs Pvt. Ltd.
      location: Surat, Gujarat
      title: Magento Developer
      started: june 2020
      duration: (2020 - 2020)
      description: Work as Magento Developer
    - work1:
      company: Cirkle Studio
      location: Surat, Gujarat
      title: Jr. Magento Developer
      started: June 2018
      duration: (2018 - 2020)
      description: Start training and work as Jr. Magento Developer

  educationHistory:
    - education1:
      organization: S.G.V.U.
      location: Jaypur, Rajasthan
      degree: Master of computer application
      major: Software Engineering
      started: 2018
      duration: (2018 - 2021)
      description: Suresh gyanvihar university
      collegeLogo: /assets/img/sgvu.png
      universityLogo: 
    - education2:
      organization: Sutex bank collage of computer application and science
      location: Shenyang, China
      degree: Bechlor of computer application
      major: Software Engineering
      started: 2015
      duration: (2015 - 2018)
      description: Veer narmad south gujarat university
      collegeLogo: /assets/img/sutex.png
      universityLogo: /assets/img/vnsgu.jpg
  languages:
    - language1:
      name: Gujarati & Hindi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: French (learner)
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: Magento 2/1
      percentage: 90%
    - skill2:
      name: Opencart 3/2
      percentage: 80%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: Codeigniter
      percentage: 80%
    - skill5:
      name: Core PHP
      percentage: 70%
    - skill6:
      name: Jekyll theme
      percentage: 50%
footerLinks:
  - link1:
    label: stack
    url: stack
  - link2:
    label: code
    url: code
  - link3:
    label: cmd
    url: cmd
  - link4:
    label: books
    url: books