# Site settings
title: Bhavesh Prajapati 
description: Bhavesh Prajapati
avtar: /assets/img/avatar.jpg
favicon: /assets/img/favicon.ico
baseurl: https://bhaveshpp.github.io
url: https://bhaveshpp.github.io
rss_url: /pages/atom.xml
google_analytics: G-EJMV7MMWDX

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Bhavesh Prajapati
  title: Professional full stack Developer (E commerce web developer)
  address: Surat, Gujarat, India
  email: bhaveshp.magento@gmail.com
  link: https://bhaveshpp.github.io
  skype: live:bhaveshpp11
  skypeurl: https://join.skype.com/invite/wBzrwCc2PXcJ
  github: bhaveshpp
  linkedin: bhavesh-prajapati-576a97171
  twitter: bhaveshpp111
  codepen: bhaveshpp
  upwork: 019837fb6268595b09
  gavatar: /assets/img/avatar.JPG
  magento_stackexchange: 70292
#  stackoverflow: 70292
  workHistory:
    - work4:
      company: Individual 
      location: Remote / Worldwide
      title: Magento Developer
      started: Dec 2021
      duration: (2020 - present)
      description: Professional full stack Developer (E commerce web developer)
    - work3:
      company: Tecksky
      location: Surat, Gujarat
      title: Magento Developer
      started: Sep 2020
      duration: (2020 - 2021)
      description: Here, I have started work as Sr. Web and Adobe Ecommerce (Magento) Developer. I have worked on magento2, magento1, codeignitor, and also on core PHP projects and learned many things in my profession and personal life also. I am grateful to my team leader and colleagues for growing me up.
    - work2:
      company: Aureate Labs Pvt. Ltd.
      location: Surat, Gujarat
      title: Magento Developer
      started: june 2020
      duration: (2020 - 2020)
      description: Here I have started work as an Adobe commerce developer (Magento developer). And Learn many new technology and working standards under experienced developers. and work with the trained team and improve my skills and work performance.
    - work1:
      company: Cirkle Studio
      location: Surat, Gujarat
      title: Jr. Magento Developer
      started: June 2018
      duration: (2018 - 2020)
      description: Start training and work as Jr. Magento Developer. After completing my bachelor's degree I have started training and my master's as literal. Here I have started my journey as a web developer, After completing my training I have started working on Magento1 and Magento2 as a junior Magento developer under an experienced development team.

  educationHistory:
    - education1:
      organization: S.G.V.U.
      location: Jaypur, Rajasthan
      degree: Master of computer application
      major: Software Engineering
      started: 2018
      duration: (2018 - 2021)
      description: Suresh gyanvihar university
      collegeLogo: /assets/img/sgvu.png
      universityLogo: 
    - education2:
      organization: Sutex bank collage of computer application and science
      location: Shenyang, China
      degree: Bechlor of computer application
      major: Software Engineering
      started: 2015
      duration: (2015 - 2018)
      description: Veer narmad south gujarat university
      collegeLogo: /assets/img/sutex.png
      universityLogo: /assets/img/vnsgu.jpg
  languages:
    - language1:
      name: Gujarati & Hindi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: French (learner)
      proficiency: Limited
    - language4:
      name: Any (With AI and google translater)
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: Magento 2/1
      percentage: 90%
    - skill2:
      name: Opencart 3/2
      percentage: 80%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: Codeigniter
      percentage: 80%
    - skill5:
      name: Core PHP
      percentage: 70%
    - skill6:
      name: Jekyll theme
      percentage: 50%
footerLinks:
  - link1:
    label: stack
    url: stack
  - link2:
    label: code
    url: code
  - link3:
    label: cmd
    url: cmd
  - link4:
    label: books
    url: books
  - link5:
    label: privacy-policy
    url: privacy-policy
